sudo: required
services:
  - docker

before_install:
  - docker build -t ajaybojedla/complex-react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run ajaybojedla/complex-react-test npm run test -- --coverage
  
after_success:
  - docker build -t ajaybojedla/multi-client ./client
  - docker build -t ajaybojedla/multi-nginx ./nginx
  - docker build -t ajaybojedla/multi-server ./server
  - docker build -t ajaybojedla/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ajaybojedla/multi-client
  - docker push ajaybojedla/multi-nginx
  - docker push ajaybojedla/multi-server
  - docker push ajaybojedla/multi-worker
  
