language: generic 
sudo: required
services:
  - docker

# before_install:
#   - docker build -t ajaybojedla/complex-react-test -f ./client/Dockerfile.dev ./client

# scripts:
#   - docker run -e CI=true ajaybojedla/complex-react-test npm test -- --coverage
  
# after_success:
before_install:  
  - docker build -t ajaybojedla/multi-client ./client
  # - docker build -t ajaybojedla/multi-nginx ./nginx
  # - docker build -t ajaybojedla/multi-server ./server
  # - docker build -t ajaybojedla/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ajaybojedla/multi-client
  # - docker push ajaybojedla/multi-server
  # - docker push ajaybojedla/multi-worker
  # - docker push ajaybojedla/multi-nginx

# deploy:
#   provider: elasticbeanstalk
#   region: 'us-east-1'
#   app: 'complex'
#   env: 'Complex-env'
#   bucket_name: 'elasticbeanstalk-us-east-1-736796324192'
#   bucket_path: 'complex'
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY

  
